services:
  db:
    image: postgres:latest
    container_name: chill_postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chill
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: chill_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
